string(TOUPPER ${board_name} BOARD_NAME_UPPERCASE)
set(${board_name}_CLASS "ESP32")
set(${board_name}_MODULE "WROVER")
set(${board_name}_FAMILY "E")
set(${board_name}_MODEL "N4R8")
set(${board_name}_CPUNAME "XTENSA_32BIT_LX6")
set(${board_name}_CPU "XTENSA_CPU_32BIT_LX6")
set(${board_name}_DEFINES -D${BOARD_NAME_UPPERCASE} -D${${board_name}_CLASS} -D${${board_name}_CLASS}${${board_name}_MODULE} -D${${board_name}_CLASS}${${board_name}_MODULE}${${board_name}_FAMILY} -D${${board_name}_CLASS}${${board_name}_MODULE}${${board_name}_FAMILY}xx -D${${board_name}_CLASS}${${board_name}_MODULE}${${board_name}_FAMILY}${${board_name}_MODEL})

set(${board_name}_TARGET "esp32")

# Work In Progress. HAL Implementations.
# Instead of using FreeRTOS, I decided to use HAL.
# To automate and support all the esp32 HAL implementations, I decided to make a tool.cmake file which does the same thing as 
# --what the esp-idf does. It checks flags and gets necessary files for specific board.
# I still need to make this esp32 board's flags appropriate. For now everything is 1.
set(${board_name}_CONFIG_HAL_WDT_USE_ROM_IMPL 1)
set(${board_name}_CONFIG_APP_BUILD_TYPE_PURE_RAM_APP 1)
set(${board_name}_CONFIG_SOC_LP_TIMER_SUPPORTED 0)

set(${board_name}_BOOTLOADER_BUILD 1)
set(${board_name}_CONFIG_SOC_FLASH_ENC_SUPPORTED 1)
set(${board_name}_CONFIG_SOC_CLK_TREE_SUPPORTED 1)

set(${board_name}_CONFIG_SOC_SYSTIMER_SUPPORTED 1)
set(${board_name}_CONFIG_HAL_SYSTIMER_USE_ROM_IMPL 1)
set(${board_name}_CONFIG_SOC_GPTIMER_SUPPORTED 1)
set(${board_name}_CONFIG_SOC_LEDC_SUPPORTED 1)
set(${board_name}_CONFIG_SOC_I2C_SUPPORTED 1)
set(${board_name}_CONFIG_SOC_RMT_SUPPORTED 1)
set(${board_name}_CONFIG_SOC_PCNT_SUPPORTED 1)
set(${board_name}_CONFIG_SOC_MCPWM_SUPPORTED 1)
set(${board_name}_CONFIG_SOC_TWAI_SUPPORTED 1)
set(${board_name}_CONFIG_SOC_GDMA_SUPPORTED 1)
set(${board_name}_CONFIG_SOC_GDMA_SUPPORT_CRC 1)
set(${board_name}_CONFIG_SOC_AHB_GDMA_VERSION 1)
set(${board_name}_CONFIG_SOC_AHB_GDMA_VERSION 1)
set(${board_name}_CONFIG_SOC_AXI_GDMA_SUPPORTED 1)
set(${board_name}_CONFIG_SOC_I2S_SUPPORTED 1)
set(${board_name}_CONFIG_SOC_SDM_SUPPORTED 1)
set(${board_name}_CONFIG_ETH_USE_ESP32_EMAC 1)
set(${board_name}_CONFIG_SOC_ETM_SUPPORTED 1)
set(${board_name}_CONFIG_SOC_PARLIO_SUPPORTED 1)
set(${board_name}_CONFIG_SOC_ADC_SUPPORTED 1)
set(${board_name}_CONFIG_SOC_ADC_DMA_SUPPORTED 1)
set(${board_name}_CONFIG_SOC_LCDCAM_SUPPORTED 1)
set(${board_name}_CONFIG_SOC_ECC_SUPPORTED 1)
set(${board_name}_CONFIG_SOC_ECDSA_SUPPORTED 1)
set(${board_name}_CONFIG_SOC_MPI_SUPPORTED 1)
set(${board_name}_CONFIG_SOC_SHA_SUPPORTED 1)
set(${board_name}_CONFIG_SOC_AES_SUPPORTED 1)
set(${board_name}_CONFIG_SOC_MODEM_CLOCK_IS_INDEPENDENT 1)
set(${board_name}_CONFIG_SOC_PAU_SUPPORTED 1)
set(${board_name}_CONFIG_SOC_BOD_SUPPORTED 1)
set(${board_name}_CONFIG_SOC_GPSPI_SUPPORTED 1)
set(${board_name}_CONFIG_SOC_SPI_SUPPORT_SLAVE_HD_VER2 1)
set(${board_name}_CONFIG_SOC_SDIO_SLAVE_SUPPORTED 1)
set(${board_name}_CONFIG_SOC_PMU_SUPPORTED 1)
set(${board_name}_CONFIG_SOC_APM_SUPPORTED 1)
set(${board_name}_CONFIG_SOC_HMAC_SUPPORTED 1)
set(${board_name}_CONFIG_SOC_DIG_SIGN_SUPPORTED 1)


include(${${board_name}_DIR}/../tool.cmake)